apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{ include "app.fullname" . }}-run-{{ .Release.Revision }}
  annotation:
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep-since: 7200
  labels:
    tekton.dev/pipeline: build-maven
#  namespace: octo-happiness
spec:
  pipelineRef:
    name: build-via-dockerfile
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: builder-pvc-2
    - configMap:
        name: maven-settings
      name: maven-settings