deployment:
    image: octo-happiness-template-java
    version: latest
    replicas: 1
    includeHealthChecks: false

config:
    greeting: 'Hello World.'

git:
    url: https://github.com/sa-mw-dach/octo-happiness-template-java.git
